---
title: "Conclusion & Discussion"
#bibliography: references.bib
author: "Niels Vullings"
bibliography: references.bib
---

```{=html}
<style>
body {
  text-align: justify;
  font-family: Times;
}

h1, .h1, h2, .h2, h3, .h3 {
  margin-top: 24px;
  font-family: Times;
}
</style>
```
```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
# klippy::klippy(color = 'darkgreen')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

------------------------------------------------------------------------

# Conclusion
