---
title: "Introduction (draft)"
#bibliography: references.bib
author: "Niels Vullings"
bibliography: references.bib
---

```{=html}
<style>
body {
text-align: justify}
</style>
```

```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
# klippy::klippy(color = 'darkgreen')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

------------------------------------------------------------------------

## Introduction

Inequalities are omnipresent in society and this does not exclude the academic world. Be it conscious or subconscious, our actions are in part shaped by bias and stereotypes (author, year). One of the most dividing lines in the 21st century is that of gender. In a study that looked at the impact that networks have on gender differences in coauthorship, it was found that representation of women matters in relation to their network access [@mcdowell2006a]. The study looked at how male and female economist PhD's have access in their networks for publications and co-authorship. They find that over time, women are less likely to coauthor and publish articles compared to men. However, they also find that this probability does dwindle by 1993. When other forms of gender differences are included, women are less likely to be "successful" in academics. Even within the social sciences, men and women do not receive the same treatment and grants, publications and upper academic positions are unequally distributed [@bellotti2022]. This concept of academic inequality has been called the *Matilda effect*, named after the *Matthew effect*, named by Robert Merton. Bellotti et al. (2022) studied the composition of male and female collaboration networks in Italy. They find persisting inequalities between men and women in terms of research funding and collaboration across all academic disciplines. They argue that their findings are generalisable to fields where collaboration is key to success.\
  From a scientific standpoint, very little studies within the collaboration literature have focused on clustering in terms of social inequalities. [@long2013bridges] wrote a systematic review on brokers in collaborative networks and how this influence the spread of information. Their conclusion is that while brokers, bridges and boundary spanners do play a critical role in spreading information throughout networks, information will spread more efficiently when networks are more close knit. However, this paper and thus the articles it has reviewed, pay little attention to who these brokers are. In organisational science, organisations are assumed to be egalitarian and thus social inequalities are deemed non existent. This study will drop this assumption in order to see whether gender inequalities play a role in the collaborative networks of academics. Specifically, this article will study how coauthorship networks of Dutch Sociologists are clustered in terms of gender.\
  Secondly, this article will look at how this gender clustering in coauthorship networks influences the prestige or success of female scholars. Previous studies pointed out that not all research is valued equally and that gender is still an indicator of this inequality [@bellotti2022; @bozeman2011men]. By studying this inequality through a social network perspective, this study will help us to see how male and female scholars relate to each other and how there preferences influence the likelihood of publishing together (or not), and will give insights into the patterns of gaining academic prestige (or not). This leads to the following research question:

-   RQ 1: How are publication networks of scholars in Sociology departments clustered in terms of gender?

-   RQ 2: To what extent does gender clustering of publication networks influence the prestige/success of female scholars?

<br>

------------------------------------------------------------------------