---
title: "Theory (draft)"
#bibliography: references.bib
author: "Niels Vullings"
bibliography: references.bib
---

```{=html}
<style>
body {
  text-align: justify;
  font-family: Times;
}

h1, .h1, h2, .h2, h3, .h3 {
  margin-top: 24px;
  font-family: Times;
}
</style>
```
```{r, globalsettings, echo=FALSE, warning=FALSE, results='hide'}
library(knitr)

knitr::opts_chunk$set(echo = TRUE)
opts_chunk$set(tidy.opts=list(width.cutoff=100),tidy=TRUE, warning = FALSE, message = FALSE,comment = "#>", cache=TRUE, class.source=c("test"), class.output=c("test2"))
options(width = 100)
rgl::setupKnitr()



colorize <- function(x, color) {sprintf("<span style='color: %s;'>%s</span>", color, x) }

```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy(position = c('top', 'right'))
# klippy::klippy(color = 'darkgreen')
#klippy::klippy(tooltip_message = 'Click to copy', tooltip_success = 'Done')
```

Last compiled on `r format(Sys.time(), '%B, %Y')`

<br>

------------------------------------------------------------------------

# Theory

## Hypothesis 1

To study how gender clustering prevail throughout collaboration networks, we must first understand how relationships in these networks manifest themselves. To explain this, I draw on the homophily principle [@mcpherson2001birds], which argues that people who are more alike are more likely to connect. In terms of gender, it means that men are more likely to interact with other men, while women are more likely to interact with other women. For this study, this implies that men will have a preference to co-author with other men, while women will have a preference to coauthor with other women. One study that looked at collaborative networks found that the gender homophily principle holds for men in particular, meaning it is mostly men who prefer to work with other men [@kwiek2021gender]. The study explains this finding with gender norms that persist in both society and academia, particularly that it is "more occupationally advantageous" for young male academics to publish with other older male academics, while for women it is more advantageous to have publications with both male and female academics. However, they also find that this finding is inversed for field which are female dominated [@kwiek2021gender], implying that it is mostly important to coauthor with a member of the majority group. This presents an interesting case, as the division of gender in the social sciences is often presented as equal, while there are still structural gender differences when it comes to positions as senior researchers and professors [@bellotti2022]. However, as the division of male and female scholars is mostly even in the social sciences [@kwiek2021gender], I argue that men and women both seek to coauthor with others who share their gender. As men are found to prefer coauthoring with other men in the literature, it will cause a selection effect where women are more likely to coauthor with other women, because there are less men available to coauthor with. As a result, more coauthorship with members of the same gender will cluster networks, because people are familiar with the work of others and, when this work is valued positively, they are more likely to maintain their ties of send ties to others who they deem to be similar. This leads to the first hypothesis:

-   *H1: People are more likely to collaborative with others of the same gender, resulting in clustered networks.*

## Hypothesis 2

As mentioned before, previous studies have found that people, but men in particular, like to collaborate and connect with people of the same gender [@mcpherson2001birds; @kwiek2021gender]. However, some studies also found that these preferences are prone to change, resulting in more egalitarian preferences [@bellotti2022; @bozeman2011men; @kwiek2021gender]. One explanation for this finding is the increased presence of women in academia and the interventions that are being put in place to suppress inequalities between men and women [@mulders2024matter; @bellotti2022; @kwiek2021gender]. These studies found that while gender inequalities are not completely fading, they are decreasing. As stated before, a reason for the gender homophily effect might be the fact that it is mostly a majority-identity effect, meaning that is mostly about being part of a majority group that influences the preferences for collaborating with people of the same gender [@kwiek2021gender]. This argument is plausible given the finding that, female gender homophily is more prevalent in academic fields that are female-dominated [@kwiek2021gender; @wang2023gender]. When we relate this to the field of sociology, which is neither male nor female-dominated, it might be possible that structural interventions to create egalitarian working environments will decrease the gender homophily over time. This leads to the following hypothesis:

-   *H2: Collaboration networks will become less clustered in terms over gender over time.*

## Hypothesis 3

The theory proposed for *Hypothesis 2*, while plausible, is nested in structural societal changes, and does not specifically explain how this changes interactions between male and female scholars. To explain how these interactions change, I build upon the Matilda effect [@knobloch2013matilda], which is derived from the Matthew effect [@merton1968matthew]. The Matthew effect proposes that previous success will lead to future success. The Matilda effect states that due to gender biases and gender inequality, male scientific work is valued more than female scientific work [@knobloch2013matilda]. As a result of this unequal evaluation of scientific achievement, male scholars gain more prestige more quickly than female scholar [@knobloch2013matilda; @bellotti2022].\
&emsp: When it comes to collaboration, people who have higher prestige are more attractive to collaborate with [@kwiek2021gender]. This means that there is a preference to collaborate with men, as they are on average more prestigious, even within the social sciences, which is relatively equally distributed in terms of gender. This is the case because there are still inequalities in terms of senior researcher positions and professorships [@kwiek2021gender; @kim2024persistent]. However, following the expectation of *Hypothesis 2*, it can be expected that as female scholars gain more prestige within the field, people will become more inclined to collaborate with female scholars. This will result in more egalitarian collaboration networks, which means clustering will decrease, as men and women will have an equal preference to work with each other. This leads to the third and last hypothesis:

-   *H3: As the prestige of female sociologists will increase, the gender clustering of collaboration networks will decrease*

------------------------------------------------------------------------
